// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace collaborative {
namespace ml {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class PB_EncodedNumber;

// ===================================================================

class PB_EncodedNumber : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.collaborative.ml.PB_EncodedNumber) */ {
 public:
  PB_EncodedNumber();
  virtual ~PB_EncodedNumber();

  PB_EncodedNumber(const PB_EncodedNumber& from);

  inline PB_EncodedNumber& operator=(const PB_EncodedNumber& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_EncodedNumber& default_instance();

  void Swap(PB_EncodedNumber* other);

  // implements Message ----------------------------------------------

  inline PB_EncodedNumber* New() const { return New(NULL); }

  PB_EncodedNumber* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_EncodedNumber& from);
  void MergeFrom(const PB_EncodedNumber& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_EncodedNumber* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string n = 1;
  void clear_n();
  static const int kNFieldNumber = 1;
  const ::std::string& n() const;
  void set_n(const ::std::string& value);
  void set_n(const char* value);
  void set_n(const char* value, size_t size);
  ::std::string* mutable_n();
  ::std::string* release_n();
  void set_allocated_n(::std::string* n);

  // optional string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // optional int32 exponent = 3;
  void clear_exponent();
  static const int kExponentFieldNumber = 3;
  ::google::protobuf::int32 exponent() const;
  void set_exponent(::google::protobuf::int32 value);

  // optional int32 type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.collaborative.ml.PB_EncodedNumber)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr n_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::int32 exponent_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static PB_EncodedNumber* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_EncodedNumber

// optional string n = 1;
inline void PB_EncodedNumber::clear_n() {
  n_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PB_EncodedNumber::n() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.n)
  return n_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PB_EncodedNumber::set_n(const ::std::string& value) {
  
  n_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.n)
}
inline void PB_EncodedNumber::set_n(const char* value) {
  
  n_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.collaborative.ml.PB_EncodedNumber.n)
}
inline void PB_EncodedNumber::set_n(const char* value, size_t size) {
  
  n_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.collaborative.ml.PB_EncodedNumber.n)
}
inline ::std::string* PB_EncodedNumber::mutable_n() {
  
  // @@protoc_insertion_point(field_mutable:com.collaborative.ml.PB_EncodedNumber.n)
  return n_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PB_EncodedNumber::release_n() {
  // @@protoc_insertion_point(field_release:com.collaborative.ml.PB_EncodedNumber.n)
  
  return n_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PB_EncodedNumber::set_allocated_n(::std::string* n) {
  if (n != NULL) {
    
  } else {
    
  }
  n_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), n);
  // @@protoc_insertion_point(field_set_allocated:com.collaborative.ml.PB_EncodedNumber.n)
}

// optional string value = 2;
inline void PB_EncodedNumber::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PB_EncodedNumber::value() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PB_EncodedNumber::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.value)
}
inline void PB_EncodedNumber::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.collaborative.ml.PB_EncodedNumber.value)
}
inline void PB_EncodedNumber::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.collaborative.ml.PB_EncodedNumber.value)
}
inline ::std::string* PB_EncodedNumber::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:com.collaborative.ml.PB_EncodedNumber.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PB_EncodedNumber::release_value() {
  // @@protoc_insertion_point(field_release:com.collaborative.ml.PB_EncodedNumber.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PB_EncodedNumber::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:com.collaborative.ml.PB_EncodedNumber.value)
}

// optional int32 exponent = 3;
inline void PB_EncodedNumber::clear_exponent() {
  exponent_ = 0;
}
inline ::google::protobuf::int32 PB_EncodedNumber::exponent() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.exponent)
  return exponent_;
}
inline void PB_EncodedNumber::set_exponent(::google::protobuf::int32 value) {
  
  exponent_ = value;
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.exponent)
}

// optional int32 type = 4;
inline void PB_EncodedNumber::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 PB_EncodedNumber::type() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.type)
  return type_;
}
inline void PB_EncodedNumber::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ml
}  // namespace collaborative
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
