// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace collaborative {
namespace ml {

namespace {

const ::google::protobuf::Descriptor* PB_EncodedNumber_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_EncodedNumber_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_common_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_common_2eproto() {
  protobuf_AddDesc_common_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "common.proto");
  GOOGLE_CHECK(file != NULL);
  PB_EncodedNumber_descriptor_ = file->message_type(0);
  static const int PB_EncodedNumber_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_EncodedNumber, n_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_EncodedNumber, value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_EncodedNumber, exponent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_EncodedNumber, type_),
  };
  PB_EncodedNumber_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PB_EncodedNumber_descriptor_,
      PB_EncodedNumber::default_instance_,
      PB_EncodedNumber_offsets_,
      -1,
      -1,
      -1,
      sizeof(PB_EncodedNumber),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_EncodedNumber, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_EncodedNumber, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_common_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PB_EncodedNumber_descriptor_, &PB_EncodedNumber::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_common_2eproto() {
  delete PB_EncodedNumber::default_instance_;
  delete PB_EncodedNumber_reflection_;
}

void protobuf_AddDesc_common_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_common_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014common.proto\022\024com.collaborative.ml\"L\n\020"
    "PB_EncodedNumber\022\t\n\001n\030\001 \001(\t\022\r\n\005value\030\002 \001"
    "(\t\022\020\n\010exponent\030\003 \001(\005\022\014\n\004type\030\004 \001(\005b\006prot"
    "o3", 122);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common.proto", &protobuf_RegisterTypes);
  PB_EncodedNumber::default_instance_ = new PB_EncodedNumber();
  PB_EncodedNumber::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_common_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_common_2eproto {
  StaticDescriptorInitializer_common_2eproto() {
    protobuf_AddDesc_common_2eproto();
  }
} static_descriptor_initializer_common_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PB_EncodedNumber::kNFieldNumber;
const int PB_EncodedNumber::kValueFieldNumber;
const int PB_EncodedNumber::kExponentFieldNumber;
const int PB_EncodedNumber::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PB_EncodedNumber::PB_EncodedNumber()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.collaborative.ml.PB_EncodedNumber)
}

void PB_EncodedNumber::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PB_EncodedNumber::PB_EncodedNumber(const PB_EncodedNumber& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:com.collaborative.ml.PB_EncodedNumber)
}

void PB_EncodedNumber::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  n_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  exponent_ = 0;
  type_ = 0;
}

PB_EncodedNumber::~PB_EncodedNumber() {
  // @@protoc_insertion_point(destructor:com.collaborative.ml.PB_EncodedNumber)
  SharedDtor();
}

void PB_EncodedNumber::SharedDtor() {
  n_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PB_EncodedNumber::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_EncodedNumber::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_EncodedNumber_descriptor_;
}

const PB_EncodedNumber& PB_EncodedNumber::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

PB_EncodedNumber* PB_EncodedNumber::default_instance_ = NULL;

PB_EncodedNumber* PB_EncodedNumber::New(::google::protobuf::Arena* arena) const {
  PB_EncodedNumber* n = new PB_EncodedNumber;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PB_EncodedNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:com.collaborative.ml.PB_EncodedNumber)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PB_EncodedNumber, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PB_EncodedNumber*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(exponent_, type_);
  n_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool PB_EncodedNumber::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.collaborative.ml.PB_EncodedNumber)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string n = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_n()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->n().data(), this->n().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.collaborative.ml.PB_EncodedNumber.n"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // optional string value = 2;
      case 2: {
        if (tag == 18) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.collaborative.ml.PB_EncodedNumber.value"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_exponent;
        break;
      }

      // optional int32 exponent = 3;
      case 3: {
        if (tag == 24) {
         parse_exponent:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &exponent_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_type;
        break;
      }

      // optional int32 type = 4;
      case 4: {
        if (tag == 32) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.collaborative.ml.PB_EncodedNumber)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.collaborative.ml.PB_EncodedNumber)
  return false;
#undef DO_
}

void PB_EncodedNumber::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.collaborative.ml.PB_EncodedNumber)
  // optional string n = 1;
  if (this->n().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->n().data(), this->n().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.collaborative.ml.PB_EncodedNumber.n");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->n(), output);
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.collaborative.ml.PB_EncodedNumber.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // optional int32 exponent = 3;
  if (this->exponent() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->exponent(), output);
  }

  // optional int32 type = 4;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->type(), output);
  }

  // @@protoc_insertion_point(serialize_end:com.collaborative.ml.PB_EncodedNumber)
}

::google::protobuf::uint8* PB_EncodedNumber::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.collaborative.ml.PB_EncodedNumber)
  // optional string n = 1;
  if (this->n().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->n().data(), this->n().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.collaborative.ml.PB_EncodedNumber.n");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->n(), target);
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.collaborative.ml.PB_EncodedNumber.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  // optional int32 exponent = 3;
  if (this->exponent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->exponent(), target);
  }

  // optional int32 type = 4;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->type(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:com.collaborative.ml.PB_EncodedNumber)
  return target;
}

int PB_EncodedNumber::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:com.collaborative.ml.PB_EncodedNumber)
  int total_size = 0;

  // optional string n = 1;
  if (this->n().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->n());
  }

  // optional string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  // optional int32 exponent = 3;
  if (this->exponent() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->exponent());
  }

  // optional int32 type = 4;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_EncodedNumber::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.collaborative.ml.PB_EncodedNumber)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PB_EncodedNumber* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PB_EncodedNumber>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.collaborative.ml.PB_EncodedNumber)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.collaborative.ml.PB_EncodedNumber)
    MergeFrom(*source);
  }
}

void PB_EncodedNumber::MergeFrom(const PB_EncodedNumber& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.collaborative.ml.PB_EncodedNumber)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.n().size() > 0) {

    n_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.n_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  if (from.exponent() != 0) {
    set_exponent(from.exponent());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void PB_EncodedNumber::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.collaborative.ml.PB_EncodedNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_EncodedNumber::CopyFrom(const PB_EncodedNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.collaborative.ml.PB_EncodedNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_EncodedNumber::IsInitialized() const {

  return true;
}

void PB_EncodedNumber::Swap(PB_EncodedNumber* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PB_EncodedNumber::InternalSwap(PB_EncodedNumber* other) {
  n_.Swap(&other->n_);
  value_.Swap(&other->value_);
  std::swap(exponent_, other->exponent_);
  std::swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PB_EncodedNumber::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_EncodedNumber_descriptor_;
  metadata.reflection = PB_EncodedNumber_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_EncodedNumber

// optional string n = 1;
void PB_EncodedNumber::clear_n() {
  n_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PB_EncodedNumber::n() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.n)
  return n_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_EncodedNumber::set_n(const ::std::string& value) {
  
  n_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.n)
}
 void PB_EncodedNumber::set_n(const char* value) {
  
  n_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.collaborative.ml.PB_EncodedNumber.n)
}
 void PB_EncodedNumber::set_n(const char* value, size_t size) {
  
  n_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.collaborative.ml.PB_EncodedNumber.n)
}
 ::std::string* PB_EncodedNumber::mutable_n() {
  
  // @@protoc_insertion_point(field_mutable:com.collaborative.ml.PB_EncodedNumber.n)
  return n_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PB_EncodedNumber::release_n() {
  // @@protoc_insertion_point(field_release:com.collaborative.ml.PB_EncodedNumber.n)
  
  return n_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_EncodedNumber::set_allocated_n(::std::string* n) {
  if (n != NULL) {
    
  } else {
    
  }
  n_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), n);
  // @@protoc_insertion_point(field_set_allocated:com.collaborative.ml.PB_EncodedNumber.n)
}

// optional string value = 2;
void PB_EncodedNumber::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PB_EncodedNumber::value() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_EncodedNumber::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.value)
}
 void PB_EncodedNumber::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.collaborative.ml.PB_EncodedNumber.value)
}
 void PB_EncodedNumber::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.collaborative.ml.PB_EncodedNumber.value)
}
 ::std::string* PB_EncodedNumber::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:com.collaborative.ml.PB_EncodedNumber.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PB_EncodedNumber::release_value() {
  // @@protoc_insertion_point(field_release:com.collaborative.ml.PB_EncodedNumber.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_EncodedNumber::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:com.collaborative.ml.PB_EncodedNumber.value)
}

// optional int32 exponent = 3;
void PB_EncodedNumber::clear_exponent() {
  exponent_ = 0;
}
 ::google::protobuf::int32 PB_EncodedNumber::exponent() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.exponent)
  return exponent_;
}
 void PB_EncodedNumber::set_exponent(::google::protobuf::int32 value) {
  
  exponent_ = value;
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.exponent)
}

// optional int32 type = 4;
void PB_EncodedNumber::clear_type() {
  type_ = 0;
}
 ::google::protobuf::int32 PB_EncodedNumber::type() const {
  // @@protoc_insertion_point(field_get:com.collaborative.ml.PB_EncodedNumber.type)
  return type_;
}
 void PB_EncodedNumber::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:com.collaborative.ml.PB_EncodedNumber.type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ml
}  // namespace collaborative
}  // namespace com

// @@protoc_insertion_point(global_scope)
